version: '2'
services:
    rhinobuy-app:
        image: rhinobuy
        external_links:
            - rhinobuy-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/rhinobuy
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8090:8090
    rhinobuy-postgresql:
        extends:
            file: postgresql.yml
            service: rhinobuy-postgresql
