version: '2'
services:
    rhinobuy-postgresql:
        container_name: rhinobuy-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/rhinobuy/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=rhinobuy
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
